export default [
  {
    id: 1,
    chip: "651322252",
    visit_purpose: "RTG łapy",
    visit_date: 1719878400,
    species: "pies",
    visit_status: "URGENT",
    owner_name: "Jan",
    owner_surname: "Nowak",
  },
  {
    id: 2,
    chip: "565641234",
    visit_purpose: "Bronchoskopia",
    visit_date: 1720137600,
    species: "kot",
    visit_status: "URGENT",
    owner_name: "Agnieszka",
    owner_surname: "Konrad",
  },
  {
    id: 3,
    chip: "478487125",
    visit_purpose: "Wizyta okulistyczna",
    visit_date: 1720137600,
    species: "kanarek",
    visit_status: "URGENT",
    owner_name: "Kamil",
    owner_surname: "Waligóra",
  },
  {
    id: 4,
    chip: "256489741",
    visit_purpose: "Szczepienie",
    visit_date: 1720310400,
    species: "pies",
    visit_status: "STABLE",
    owner_name: "Andrzej",
    owner_surname: "Kowalski",
  },
  {
    id: 5,
    chip: "322897777",
    visit_purpose: "Echo serca",
    visit_date: 1720656000,
    species: "kot",
    visit_status: "URGENT",
    owner_name: "Grażyna",
    owner_surname: "Szynka",
  },
  {
    id: 6,
    chip: "984262669",
    visit_purpose: "Szczepienie",
    visit_date: 1720742400,
    species: "Kawia domowa",
    visit_status: "STABLE",
    owner_name: "Jan",
    owner_surname: "Górka",
  },
  {
    id: 7,
    chip: "444548518",
    visit_purpose: "USG jamy brzusznej",
    visit_date: 1721088000,
    species: "kot",
    visit_status: "STABLE",
    owner_name: "Mateusz",
    owner_surname: "Szczepaniak",
  },
  {
    id: 8,
    chip: "515155547",
    visit_purpose: "RTG kręgosłupa",
    visit_date: 1721606400,
    species: "pies",
    visit_status: "STABLE",
    owner_name: "Miłosz",
    owner_surname: "Firek",
  },
  {
    id: 9,
    chip: "234146647",
    visit_purpose: "Kastracja",
    visit_date: 1722470400,
    species: "kot",
    visit_status: "STABLE",
    owner_name: "Anna",
    owner_surname: "Kasprzyk",
  },
  {
    id: 10,
    chip: "654444457",
    visit_purpose: "Szczepienie",
    visit_date: 1722556800,
    species: "pies",
    visit_status: "STABLE",
    owner_name: "Jadwiga",
    owner_surname: "Cieślak",
  },
];
