export default [
  {
    id: 1,
    chip_number: "651322252",
    visit_purpose: "RTG łapy",
    visit_date: 1719878400,
    species: "pies",
    status: "URGENT",
    name: "Jan",
    surname: "Nowak",
  },
  {
    id: 2,
    chip_number: "565641234",
    visit_purpose: "Bronchoskopia",
    visit_date: 1720137600,
    species: "kot",
    status: "URGENT",
    name: "Agnieszka",
    surname: "Konrad",
  },
  {
    id: 3,
    chip_number: "478487125",
    visit_purpose: "Wizyta okulistyczna",
    visit_date: 1720137600,
    species: "kanarek",
    status: "URGENT",
    name: "Kamil",
    surname: "Waligóra",
  },
  {
    id: 4,
    chip_number: "256489741",
    visit_purpose: "Szczepienie",
    visit_date: 1720310400,
    species: "pies",
    status: "STABLE",
    name: "Andrzej",
    surname: "Kowalski",
  },
  {
    id: 5,
    chip_number: "322897777",
    visit_purpose: "Echo serca",
    visit_date: 1720656000,
    species: "kot",
    status: "URGENT",
    name: "Grażyna",
    surname: "Szynka",
  },
  {
    id: 6,
    chip_number: "984262669",
    visit_purpose: "Szczepienie",
    visit_date: 1720742400,
    species: "Kawia domowa",
    status: "STABLE",
    name: "Jan",
    surname: "Górka",
  },
  {
    id: 7,
    chip_number: "444548518",
    visit_purpose: "USG jamy brzusznej",
    visit_date: 1721088000,
    species: "kot",
    status: "STABLE",
    name: "Mateusz",
    surname: "Szczepaniak",
  },
  {
    id: 8,
    chip_number: "515155547",
    visit_purpose: "RTG kręgosłupa",
    visit_date: 1721606400,
    species: "pies",
    status: "STABLE",
    name: "Miłosz",
    surname: "Firek",
  },
  {
    id: 9,
    chip_number: "234146647",
    visit_purpose: "Kastracja",
    visit_date: 1722470400,
    species: "kot",
    status: "STABLE",
    name: "Anna",
    surname: "Kasprzyk",
  },
  {
    id: 10,
    chip_number: "654444457",
    visit_purpose: "Szczepienie",
    visit_date: 1722556800,
    species: "pies",
    status: "STABLE",
    name: "Jadwiga",
    surname: "Cieślak",
  },
];
